---
title: "RWorksheet_Callao#4a"
author: "shan"
date: "2023-10-25"
output: pdf_document
---

#1
#A
``` {r num1a}
ShoeSize <- c(6.5, 9.0, 8.5, 8.5, 10.5, 10.5, 8.5, 12.0, 10.5, 8.5)
Height <- c(66.0, 68.0, 64.5, 65.0, 70.0, 64.0, 74.0, 67.0, 71.0, 71.0)

df <- data.frame(ShoeSize, Height)
print(df)
```

#B
``` {r num1b}
males <- subset(df, ShoeSize>=9)
females <- subset(df, ShoeSize<9)

print(males)
print(females)
```
# The resulting subsets would be:
```
  ShoeSize Height
2      9.0   68.0
5     10.5   70.0
6     10.5   64.0
8     12.0   67.0
9     10.5   71.0

  ShoeSize Height
1      6.5   66.0
3      8.5   64.5
4      8.5   65.0
7      8.5   74.0
10     8.5   71.0
```

#C
``` {r num1c}
mean(df$ShoeSize)
# 9.3
mean(df$Height)
# 68.05
```

#d
``` {r num1d}
plot(df$ShoeSize, df$Height, xlab="Shoe Size", ylab="Height")
```

#FACTORS

#2
``` {r num2}
months_vector <- c("March","April","January","November","January",
                    "September","October","September","November","August",
                    "January","November","November","February","May","August",
                    "July","December","August","August","September","November","February","April")
factor_months_vector <- factor(months_vector)
print(factor_months_vector)
```

#3
``` {r num3}
summary(months_vector)
# Length     Class      Mode 
#     24 character character 

summary(factor_months_vector)
# April    August  December  February   January      July     March       May  November   October September 
#      2        4         1         2         3        1         1         1         4         1         3 
# There are 12 unique month names in the months_vector, whereas there are 11 unique levels in factor_months_vector. 
#In this case, the factor vector is more useful as it allows for easier analysis of the frequency of each month.
```

#4
``` {r num4}
direction_vector <- c("East", "West", "North")
frequency_vector <- c(1,4,3)

factor_data <- factor(direction_vector, levels = c("East", "West", "North"))
new_order_data <- factor(factor_data,levels = c("East","West","North"))

print(factor_data)
print(new_order_data)
```


``` {r num5}
#5.
student_table <- read.table(file = 'import_march.csv', header = TRUE, sep = ',')
student_table
```

``` {r num6}
#6.
random_number <- sample(1:50, 1)

cat("The chosen number is:", random_number, "\n")

if (random_number == 20) {
  cat("TRUE\n")
} else if (random_number < 1 || random_number > 50) {
  cat("The number selected is beyond the range of 1 to 50\n")
} else {
  cat(random_number, "\n")
}
```

``` {r num7}
#7.
calculate_min_bills <- function(price_of_snack) {
  bill_denominations <- c(1000, 500, 200, 100, 50)
  total_bills <- 0
  
  for (bill in bill_denominations) {
    num_bills_needed <- price_of_snack %/% bill
    price_of_snack <- price_of_snack %% bill
    total_bills <- total_bills + num_bills_needed
  }
  
  cat("Minimum number of bills needed to purchase the snack:", total_bills, "\n")
}

price_of_snack <- 1350
calculate_min_bills(price_of_snack)
```

``` {r num8a}
#8.
#a.
students <- data.frame(
  Name = c("Annie" , "Thea", "Steve", "Hanna"),
  Grade1 = c(85,65,75,95),
  Grade2 = c(65,75,55,75),
  Grade3 = c(85,90,80,100),
  Grade4 = c(100,90,85,90)
)
students
```

``` {r num8b}
#b.

students$Average <- (students$Grade1 + students$Grade2 + students$Grade3 + students$Grade4) / 4

for (i in 1:nrow(students)) {
  if (students$Average[i] > 90) {
    cat(students$Name[i], "'s average grade this semester is", students$Average[i], "\n")
  }
}
```

``` {r num8c}
#c
test1_average <- sum(students$Grade1) / nrow(students)
test2_average <- sum(students$Grade2) / nrow(students)
test3_average <- sum(students$Grade3) / nrow(students)
test4_average <- sum(students$Grade4) / nrow(students)

if (test1_average < 80) {
  cat("The 1st test was difficult.\n")
}
if (test2_average < 80) {
  cat("The 2nd test was difficult.\n")
}
if (test3_average < 80) {
  cat("The 3rd test was difficult.\n")
}
if (test4_average < 80) {
  cat("The 4th test was difficult.\n")
}
```

``` {r num8d}
#d.
for (i in 1:nrow(students)) {
  highest_grade <- students$Grade1[i]
  if (students$Grade2[i] > highest_grade) {
    highest_grade <- students$Grade2[i]
  }
  if (students$Grade3[i] > highest_grade) {
    highest_grade <- students$Grade3[i]
  }
  if (students$Grade4[i] > highest_grade) {
    highest_grade <- students$Grade4[i]
  }
  if (highest_grade > 90) {
    cat(students$Name[i], "'s highest grade this semester is", highest_grade, "\n")
  }
}

```


